var a = 3;
var b = 5;
var c;
var result = "";
result += 'var a = 3;\n';
result += 'var b = 5;\n';
result += 'var c;\n';
result += '----------\n';
result += 'a + b = ' + (a + b) + '\n';
result += 'a - b = ' + (a - b) + '\n';
result += 'a * b = ' + (a * b) + '\n';
result += 'a / b = ' + (a / b) + '\n';
result += 'a % b = ' + (a % b) + '\n';
result += 'a += b = ' + (a += b) + '\n';
result += 'a -= b = ' + (a -= b) + '\n';
result += 'a *= b = ' + (a *= b) + '\n';
result += 'a /= b = ' + (a /= b) + '\n';
result += 'a %= b = ' + (a %= b) + '\n';
result += 'a == b = ' + (a == b) + '\n';
result += 'a != b = ' + (a != b) + '\n';
result += 'a > b = ' + (a > b) + '\n';
result += 'a < b = ' + (a < b) + '\n';
result += '!a && !c = ' + (!a && !c) + '\n';
result += '!a || !c = ' + (!a || !c) + '\n';
alert(result);
